### ISSUE TITLE
protocol optimization: verify hash that derives view key in contract, instead of the public key, saving on *lots* of gas

### ISSUE THREAD

**Issue by noot** [noot/atomic-swap#36]
I propose an update to the existing swap protocol that will dramatically reduce the gas costs to deploy the contract and call Claim/Refund.

the current protocol verifies that the secret passed to the contract (either `s_a` or `s_b`) corresponds to the public key of either Alice or Bob (that was set when the contract was deployed) by performing an ed25519 scalar base multiplication and checking that the resulting point == the public key. this is expensive (around 1mil gas currently)

however, this can be replaced by only verifying a keccak256 hash (30 gas!!)

for background, a monero private view key is derived from the private spend key as follows:
```
func (k *PrivateSpendKey) View() (*PrivateViewKey, error) {
	h := Keccak256(k.key.Bytes())
	vk, err := ed25519.NewScalar().SetBytesWithClamping(h[:])
	if err != nil {
		return nil, err
	}

	return &PrivateViewKey{
		key: vk,
	}, nil
}
```

first, the spend key is hashed using keccak256 and then set to a point on the ed25519 curve using clamping. the resulting scalar is the view key.

the updated protocol is as follows:
1. in the key exchange step, Alice and Bob exchange public spend keys (`P_a` and `P_b`) and private view keys (`v_a` and `v_b`), and additionally the keccak256-hashes of their private spend keys (`h_a` and `h_b`) that are used to derive their private view keys. when each party receives the other party's keys, they verify that the hash they receive corresponds to the view key.
2. Alice deploys a Swap contract storing the keccak256 hashes `h_a` and `h_b` in the contract. Claim can be called by revealing the pre-image to `h_b` (ie. `s_b`) and Refund can be called by revealing the pre-image to `h_a` (ie. `s_a`)
3. the rest of the protocol proceeds as usual - Bob locks his XMR in the account `P_a + P_b`, which is viewable with `v_a + v_b` and spendable with `s_a + s_b`. either Claim or Refund will be called on the contract, and thus one party will end up with the spend key to the account at completion of the protocol.

note: we don't verify in step 1 that the view key corresponds to the public spend key, as it's impossible to do so. however, if the public spend key does not correspond to the view key, then the funds cannot be viewed. before Bob locks his XMR, he can check that he can generate a view-only wallet using the summation of the two view keys. if he cannot, he should abort the protocol as the view keys and public keys do not correspond. or, on Alice's side, if she cannot view the funds after they are locked (as the view keys are wrong), she should abort.

implications:
- the only drawback I see to this method is that both Alice and Bob now have the secret view key to the account with the locked XMR, so at the end of the protocol, now both Alice and Bob can view when the funds are transferred out. I don't see this being an issue, as Alice can just transfer the funds to another account once the swap is done if she wishes. either way, both parties know of the amount being swapped to begin with, so it doesn't really reduce privacy imo.
- actually, as the libp2p messages aren't encrypted, there's a chance *anyone* can get the secret view keys and create a view-only wallet for the account. however if someone intercepts the messages between Alice and Bob, they also already know of the amounts transferred and where. so, as long as Alice transfers her funds out after the swap (if she cares about someone viewing the account), I think this is ok.

I'll work on updating the contract/code for this and reply with the benchmark updates. and of course, let me know if there are security issuse with this proposed update.

**Comment by TheCharlatan** [comment]
To me it seems like there is nothing enforcing that the preimage of `h_a` is actually corresponding to the private key of the public key `P_a`. The derivation of the private view key from the private spend key is just convention and not using this convention will still produce valid Monero transactions. In this case, Bob could could end up locking the Monero with another spend key `s_c`, without Alice noticing it. Due to the nature of Monero spend keys, she would only notice once she tries to spend the Monero. 

> however, if the public spend key does not correspond to the view key, then the funds cannot be viewed. before Bob locks his XMR, he can check that he can generate a view-only wallet using the summation of the two view keys.

The `monero-wallet-rpc` for example will happily find transactions that do not actually correspond to the spend key you have imported, as long as the view key matches.

I would like to take this opportunity to publicly invite you to continue your work as part of the Farcaster project. We definitely have a common goal, and our experiences seem to intersect nicely. Obviously I see that joining another team's half-finished project in a language that is not your first preference is by no means the most appealing thing to do, especially after having written a lot of code yourself, but I feel like this effort and especially the cryptography is best done in a group on a shared codebase. We are also keen to extend the extensive modelling and specs written by us since the publishing of the original Monero<->Bitcoin atomic swaps paper by h4sh3d to Monero<->Ethereum swaps. If you are interested in formalizing a model of your swap, contact us on #monero-swap on libera.chat.

**Comment by noot** [comment]
> To me it seems like there is nothing enforcing that the preimage of `h_a` is actually corresponding to the private key of the public key `P_a`. The derivation of the private view key from the private spend key is just convention and not using this convention will still produce valid Monero transactions. In this case, Bob could could end up locking the Monero with another spend key `s_c`, without Alice noticing it. Due to the nature of Monero spend keys, she would only notice once she tries to spend the Monero.
> 
> The `monero-wallet-rpc` for example will happily find transactions that do not actually correspond to the spend key you have imported, as long as the view key matches.

ah, I see what you mean, you can generate a wallet where the spend key, view key, and address don't correspond. I thought I had figured out a nice gas workaround, oh well lol. thanks for pointing this out!

> I would like to take this opportunity to publicly invite you to continue your work as part of the Farcaster project. We definitely have a common goal, and our experiences seem to intersect nicely. Obviously I see that joining another team's half-finished project in a language that is not your first preference is by no means the most appealing thing to do, especially after having written a lot of code yourself, but I feel like this effort and especially the cryptography is best done in a group on a shared codebase. We are also keen to extend the extensive modelling and specs written by us since the publishing of the original Monero<->Bitcoin atomic swaps paper by h4sh3d to Monero<->Ethereum swaps. If you are interested in formalizing a model of your swap, contact us on #monero-swap on libera.chat.

I'm definitely interested in talking and seeing where we can work together when possible :) I'll reach out to you soon.
