### ISSUE TITLE
protocol fix: Alice must provide proof of knowledge of her private key

### ISSUE THREAD

**Issue by noot** [noot/atomic-swap#60]
currently, the first step of the protocol (key exchange phase) does not require either party to go first. however, there is a potential attack where if Bob sends his public key `P_b = G*s_b` first, Alice sends back `P_a = -P_b + P_a'` where the secret is then `-s_b + s_a'`. after Alice locks her eth, Bob then locks his monero in the account `P_a + P_b = -P_b + P_a' + P_b = P_a' = G*s_a'`. since Alice knows `s_a'` she can unlock the monero as well as the eth. 

to prevent this from happening, either Alice can be forced to send keys first (a bit hacky, not preferred), or Alice must send a proof of knowledge of the private key corresponding to `P_a` along with her keys. this proof of knowledege can take the form `P_a.sign(P_a)` (ie. a signature of `P_a`, signed with `s_a`). since Alice does not know `s_b` this prevents the above attack from occuring.

thanks to @kayabaNerve for pointing this out!

**Comment by kayabaNerve** [comment]
To expand, Bob has the exact same ability. Under the current flow, Bob's sole knowledge of the Monero TX key isn't beneficial. To claim the ETH, they have to publish their secret key share, which they don't know because their secret key share is -a+b, and Alice only reveals her key when calling refund (which has an exclusive timelock and cannot be frontrun with a call to claim assuming a properly coded app). Because of that, the protocol is doomed to end up with both parties calling refund, and Bob's sole knowledge of the XMR key just voids the need for Alice to publish her share.

The modern DLEq proof is extended with a proof of knowledge so implementing it instead of the current on chain solution would also be sufficient to resolving this. The proof of knowledge is a signature for both curves, yet only an Ed25519 signature is needed here.

Happy to help!
